### ISSUE TITLE
An exception or error caused a run to abort.  java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by tribbloid** [bmc/classutil#21]
the following code in a class constructor executed in IntelliJ IDEA 14.1:

class TestAllTransformers extends SpookyEnvSuite {

  val files = sys.props("java.class.path").split(":").map(new File(_)).filter(_.exists())
  val finder: ClassFinder = ClassFinder(files)
  val classes: Iterator[ClassInfo] = finder.getClasses().iterator

 results in the following error:

An exception or error caused a run to abort. 
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at org.clapper.classutil.asm.ClassFile$.load(ClassFinderImpl.scala:189)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$classData(ClassFinder.scala:406)
	at org.clapper.classutil.ClassFinder$$anonfun$2.apply(ClassFinder.scala:364)
	at org.clapper.classutil.ClassFinder$$anonfun$2.apply(ClassFinder.scala:364)
	at scala.collection.immutable.Stream.map(Stream.scala:376)
	at org.clapper.classutil.ClassFinder.processOpenZip(ClassFinder.scala:364)
	at org.clapper.classutil.ClassFinder.processJar(ClassFinder.scala:318)
	at org.clapper.classutil.ClassFinder.findClassesIn(ClassFinder.scala:307)
	at org.clapper.classutil.ClassFinder.find(ClassFinder.scala:299)
	at org.clapper.classutil.ClassFinder.find(ClassFinder.scala:299)
	at org.clapper.classutil.ClassFinder.find(ClassFinder.scala:299)
	at org.clapper.classutil.ClassFinder.find(ClassFinder.scala:299)
	at org.clapper.classutil.ClassFinder.getClasses(ClassFinder.scala:289)
	at com.tribbloids.spookystuff.pipeline.TestAllTransformers.<init>(TestAllTransformers.scala:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:2644)
	at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2461)
	at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2460)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2460)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

Process finished with exit code 0

**Comment by bmc** [comment]
Cannot reproduce with 1.0.7 or 1.0.8 (which I'm about to release). Please reopen if you run into it again, and please include the version that fails.
