### ISSUE TITLE
 UnsupportedOperationException

### ISSUE THREAD

**Issue by vimalaguti** [bmc/classutil#29]
Hi, I get this error, do you know any solution?

scala 2.11.12
org.ow2.asm 6.1.1
classutil 2.11-1.3.0

what I do is just:
`val finder = ClassFinder()
  val classes = finder.getClasses()`
and then broke

`An exception or error caused a run to abort. 
java.lang.UnsupportedOperationException
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:129)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:667)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:503)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:355)
	at org.clapper.classutil.asm.ClassFile$.load(ClassFinderImpl.scala:261)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$classData(ClassFinder.scala:428)
	at org.clapper.classutil.ClassFinder$$anonfun$2.apply(ClassFinder.scala:386)
	at org.clapper.classutil.ClassFinder$$anonfun$2.apply(ClassFinder.scala:386)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at org.clapper.classutil.ClassFinder.processOpenZip(ClassFinder.scala:386)
	at org.clapper.classutil.ClassFinder.processJar(ClassFinder.scala:344)
	at org.clapper.classutil.ClassFinder.findClassesIn(ClassFinder.scala:333)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.org$clapper$classutil$ClassFinder$$find(ClassFinder.scala:325)
	at org.clapper.classutil.ClassFinder.getClasses(ClassFinder.scala:315)
	at com.myproject.getAllConfs(myproject.scala:46)
	at com.myproject.<init>(myproject.scala:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1422)
	at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1236)
	at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1235)
	at scala.collection.immutable.List.map(List.scala:284)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1235)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
`

**Comment by agubelu** [comment]
I'm having the exact same error on the same Scala/ClassUtil versions.

**Comment by FloWi** [comment]
I had the same problem. I found out that I had a version conflict with the asm-dependency in my classpath, since the cassandra driver already includes `asm`. Fixed it by using this exclusion rule in my `build.sbt`

```scala
        "org.clapper" %% "classutil" % "1.3.0" excludeAll(
          ExclusionRule(organization = "org.ow2.asm") //since cassandra-driver already provides this dependency
        )

```

**Comment by bmc** [comment]
This comes up a lot. What @FloWi suggests is the correct answer, I think. The other alternative that springs immediately to mind—creating a fatter `classutil` jar with a shaded version of ASM—doesn't feel right to me.

**Comment by FloWi** [comment]
I now encounter the same problem as mentioned above. I found another bug for which I wanted to create a small example. Would you mind taking a look in my [example repo here](https://github.com/FloWi/classUtil-bug) to see what I (and maybe the others above) did wrong?

**Comment by FloWi** [comment]
I think the problem lies here:
https://github.com/bmc/classutil/blob/master/src/main/scala/org/clapper/classutil/asm/ASMEmptyVisitor.scala#L10
You set the api-version to Opcodes.ASM4 - but asm throws an exception, when the api-version is < Opcodes.ASM6. In your documentation you write asm "version 4 or better" - right now it's only compatible with version 4.

**Comment by FloWi** [comment]
I was able to reproduce the bug in your testsuite. Please take a look at my fork.
https://github.com/FloWi/classutil/tree/broken-classfinder-get-classes

I added a failing testcase that doesn't use the `runtimeClassfinder` you use in all the tests. I guess we somehow have to figure out what the current version of ASM is and instantiate the `org.clapper.classutil.asm.ASMEmptyVisitor` with this apiVersion.

**Comment by FloWi** [comment]
created a pull request that solves the problem. Please take a look on what you think about my solution. Should be backwards compatible.
